### ISSUE TITLE
Need <stem> element within note

### ISSUE THREAD

**Issue by DILewis** [music-encoding/mensural-ig#1]
Additional element needed to encode notes with two stems, or with modified stems (e.g. direction, presence of flags of different kinds) that carry a mensural significance. Attributes describe direction, position, and form of the stem, form and direction of flag(s). 

 - NEW optional element `<stem>`, contained by `<note>` likely to be employed as a pair

 - WITH optional attribute  `@pos`  (`left` | `right` | `center` )  relative to the note head
 - WITH optional attribute `@length`  `data.MEASUREMENTABS`
 - WITH optional attribute  `@form`  (`circle` | `oblique` | `swallowtail` | `virgula` )  default: normal stem
 - WITH optional attribute  `@dir`  ( `up` | `down` | `left` | `right` | `ne` | `se` | `nw` | `sw` ) [values are already in use in data.STEMDIRECTION.basic and data.STEMDIRECTION.extended]
 - WITH optional attribute `@flag.pos`  (`left` | `right` | `center` )    relative to the outer end of the stem
 - WITH optional attribute `@flag.form`  ( `straight` | `angled` | `curled` | `flared` | `extended` | `hooked`  )
 - WITH optional attribute `@x`
 - WITH optional attribute `@y`

**Comment by DILewis** [comment]
Examples for each attribute, and images for `@form` would be helpful. Also, should `@dir` be a data.compassDirection? (e.g. `up` => `n`, `left` => `w`)

**Comment by rettinghaus** [comment]
Closing this, as implemented in https://music-encoding.org/guidelines/dev/attribute-classes/att.stem.vis.html

@DILewis Could you please provide example images (especially for `@flag.form`) for documentation?
