### ISSUE TITLE
Support long rests lasting two or three breves

### ISSUE THREAD

**Issue by DILewis** [music-encoding/mensural-ig#3]
To support 2-breve and 3-breve rests, we need new values to be made available in `@dur`.
 - Add values ( `2B` | `3B` ) to `data.DURATION.mensural`
 - Affects `rest` element only (Schematron rule)
 - Used only in `@dur` of rests

**Comment by DILewis** [comment]
Do we have an example for how maxima rests should work (i.e. two or three `2B` or `3B` rests in a group)?

**Comment by martha-thomae** [comment]
Is anyone familiar with Schematron rules? 
I was including support for handling this and other issues in the schema ([pull request here](https://github.com/music-encoding/music-encoding/pull/634)), but I think that the way I handle this particular issue needs improvement. I did a whole workaround to get the `2B` and `3B` values restricted to the `<rest>` elements (no need to see that) instead of implementing a Schematron rule for this. I want to change that. I want to use Schematron to handle this issue but I have no experience with it. The following code would be my proposal to handle this. It doesn't work yet. Can anyone with experience in Schematron take a look at it and indicate me what is wrong and how to make it work? Thanks!
```xml
<macroSpec ident="data.DURATION.mensural" module="MEI.mensural" type="dt" mode="change">
  <desc>Logical, that is, written, note-shape (or note symbol) attribute values for the mensural repertoire.</desc>
  <content>
    <valList type="closed">
      <valItem ident="maxima">
        <desc>Two or three times as long as a longa.</desc>
      </valItem>
      <valItem ident="longa">
        <desc>Two or three times as long as a brevis.</desc>
      </valItem>
      <valItem ident="brevis">
        <desc>Two or three times as long as a semibrevis.</desc>
      </valItem>
      <valItem ident="semibrevis">
        <desc>Half or one-third as long as a breve/brevis.</desc>
      </valItem>
      <valItem ident="minima">
        <desc>Half or one-third as long as a semibreve/semibrevis.</desc>
      </valItem>
      <valItem ident="semiminima">
        <desc>Half as long as a minima.</desc>
      </valItem>
      <valItem ident="fusa">
        <desc>Half as long as a semiminima.</desc>
      </valItem>
      <valItem ident="semifusa">
        <desc>Half as long as a fusa.</desc>
      </valItem>
      <valItem ident="2B" mode="add">
        <desc>Two-breve rest.</desc>
      </valItem>
      <valItem ident="3B" mode="add">
        <desc>Three-breve rest.</desc>
      </valItem>
    </valList>
  </content>
  <constraintSpec ident="multibreve_rests_only" scheme="isoschematron" mode="add">
    <constraint>
      <sch:rule context="note/@dur">
        <sch:assert test="not('2B','3B')">Values not permitted for note elements</sch:assert>
      </sch:rule>
    </constraint>
  </constraintSpec>
</macroSpec>
```

**Comment by annplaksin** [comment]
So, I tried it... somehow, the constraint only worked for me outside of `<macroSpec>`, but I don't know why.

And I tweaked it a little bit to get it work:
```xml
<constraintSpec ident="multibreve_rests_only" scheme="isoschematron" mode="add">
    <constraint>
        <sch:rule context="mei:note">
            <sch:assert test="not(@dur='2B' or @dur='3B')">Values not permitted for note elements</sch:assert>
        </sch:rule>
    </constraint>
</constraintSpec>
```
You need to give the element with namespace in `@context`.
It didn't like having the attribute in the rule and only the value definition in `<assert>`.

Even if I played around with customisations in the last years I would not call me an expert. Maybe @kepper or @bwbohl have deeper insights into the strange mechanics and could help with a better solution or an explanation why things won't work.

Hope I could help at least a bit.

**Comment by martha-thomae** [comment]
Thank you for taking a look into this, Anna. I will try this, then. Thanks!

**Comment by martha-thomae** [comment]
Hi @annplaksin. I tried what you said, changed the information provided in the `context` within `<sch:rule> `and also the one in `test` within `<sch:assert>`. And I moved the constraint outside `<macroSpec>`. 

You said it worked for you, right? It is not working for me still. The values "2B" and "3B" are still valid in both `<note>` and `<rest>` elements. I am attaching here the customization file (_mei-Mensural.xml_). Only lines 108–151 are changed from the original customization file in the music-encoding repo. Do you happen to see something wrong with it? Do you still have the file where you tested the constraint? I can compare the two (yours and mine) to see if I am missing something else to make mine work. I attached a _Proof.mei_ file where you can see that both `<note dur="2B">` and `<rest dur="2B">` are valid using the schema (_MensuralSchema.rng_) generated with this customization (_mei-Mensural.xml_).

Does anyone else have some ideas regarding why the constraint is not working? @ahankinson, @kepper, or @bwbohl perhaps?

Thank you in advance!

[Customization_Schema_and_ExampleMEIfile.zip](https://github.com/music-encoding/mensural-ig/files/4183755/Customization_Schema_and_ExampleMEIfile.zip)

**Comment by martha-thomae** [comment]
If it is easier to see here, the content of those lines (108–151) is:
```xml
<macroSpec ident="data.DURATION.mensural" module="MEI.mensural" type="dt" mode="change">
  <desc>Logical, that is, written, note-shape (or note symbol) attribute values for the mensural repertoire.</desc>
  <content>
    <valList type="closed">
      <valItem ident="maxima">
        <desc>Two or three times as long as a longa.</desc>
      </valItem>
      <valItem ident="longa">
        <desc>Two or three times as long as a brevis.</desc>
      </valItem>
      <valItem ident="brevis">
        <desc>Two or three times as long as a semibrevis.</desc>
      </valItem>
      <valItem ident="semibrevis">
        <desc>Half or one-third as long as a breve/brevis.</desc>
      </valItem>
      <valItem ident="minima">
        <desc>Half or one-third as long as a semibreve/semibrevis.</desc>
      </valItem>
      <valItem ident="semiminima">
        <desc>Half as long as a minima.</desc>
      </valItem>
      <valItem ident="fusa">
        <desc>Half as long as a semiminima.</desc>
      </valItem>
      <valItem ident="semifusa">
        <desc>Half as long as a fusa.</desc>
      </valItem>
      <valItem ident="2B" mode="add">
        <desc>Two-breve rest.</desc>
      </valItem>
      <valItem ident="3B" mode="add">
        <desc>Three-breve rest.</desc>
      </valItem>
    </valList>
  </content>
</macroSpec>
<constraintSpec ident="multibreve_rests_only" scheme="isoschematron" mode="add">
  <constraint>
    <sch:rule context="mei:note">
      <sch:assert test="not(@dur='2B' or @dur='3B')">Values not permitted for note elements.</sch:assert>
    </sch:rule>
  </constraint>
</constraintSpec>
```

**Comment by annplaksin** [comment]
Thanks for sharing your files with me. It might have found a reason why it's not working.
In your Proof.mei file, the schematron association is missing. I added that and it worked.

Without the second line, there will be no schematron validation:
```xml
<?xml-model href="MensuralSchema.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="MensuralSchema.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

But the `<constraintSpec>` still needs to be outside `<macroSpec>`, It again tested it with your file.

**Comment by martha-thomae** [comment]
Oooops! Thanks, @annplaksin!

**Comment by annplaksin** [comment]
No problem, you're welcome. If there are any other thing, I can help with, feel free to ask. :-)
