### ISSUE TITLE
att.note.anl.mensural needs revision

### ISSUE THREAD

**Issue by lpugin** [music-encoding/mensural-ig#5]
There are a couple of points that need revision regarding this (@lig) attribute used by `<note>`.
https://music-encoding.org/guidelines/v4/attribute-classes/att.note.anl.mensural.html
As far as I understand, it is available to encode the visual aspect of ligatures with more than one note and that include oblique pairs. There is no other way to encode this visual characteristic. However, as it stands, the attribute is meant to be part of the analytical domain when this specific use clearly deals with the visual aspect of the ligature.

If using `@lig='oblique'` in notes within a ligature to encoded the visual aspect is not appropriate, then we are missing something. If not, then we should move the attribute class and rephrase its description. We should also use the existing data type 
https://music-encoding.org/guidelines/v4/data-types/data.ligatureform.html

**Comment by annplaksin** [comment]
Do I understand correctly, that you would like to have `@lig` in the visual domain?  
In that case, I would strongly agree.

Moreover, `@form` used for `<ligature>` is part of **att.ligature.log** and uses **data.ligatureform** as well.

**Comment by lpugin** [comment]
> Do I understand correctly, that you would like to have @lig in the visual domain?
In that case, I would strongly agree.

Fine. But then, may I ask how you would encode this ligature? Maybe I am overlooking something.

![image](https://user-images.githubusercontent.com/689412/81089699-f31eb480-8efc-11ea-8f2b-3679055e691d.png)

**Comment by lig** [comment]
:) You all do realize that @lig mentions me, right?

**Comment by martha-thomae** [comment]
Hi @annplaksin. Hi @lpugin.

Are you suggesting that both `@form` (attribute of `<ligature>`) and `@lig` (attribute of `<note>`) should be moved into the visual domain?

So, move:

- `@form` into the `att.ligature.vis` (rather than the `att.ligature.log` where it is now)?
- And `@lig` into something like `att.note.vis.mensural`, which I think doesn't exist, I only see `att.note.vis.cmn` (rather than the `att.note.anl.mensural` where it is now). Should we create this new class `att.note.vis.mensural` or is there something I am missing within the schema that is already appropriate for this?

And, yes, both should use the data type `data.LIGATUREFORM`.

**Comment by martha-thomae** [comment]
> > Do I understand correctly, that you would like to have `@lig` in the visual domain?
> > In that case, I would strongly agree.
> 
> Fine. But then, may I ask how you would encode this ligature? Maybe I am overlooking something.
> 
> ![image](https://user-images.githubusercontent.com/689412/81089699-f31eb480-8efc-11ea-8f2b-3679055e691d.png)

I would encode it as:
``` xml
<ligature form="recta">
  <note pname="a" oct="4" dur="longa"/>
  <note pname="f" oct="4" dur="brevis" lig="obliqua"/>
  <note pname="d" oct="4" dur="brevis" lig="obliqua"/>
  <note pname="f" oct="4" dur="brevis"/>
  <note pname="a" oct="4" dur="brevis"/>
  <note pname="c" oct="5" dur="brevis" lig="obliqua"/>
  <note pname="a" oct="4" dur="brevis" lig="obliqua"/>
  <note pname="c" oct="5" dur="longa"/>
</ligature>
```
Does this have anything to do with the visual vs. analyticial domain discussion? I might have missed the point here.
